#!/bin/bash

#TODO: make it more simple

if ! [ $# -eq 1 ]; then
	echo "Usage: $0 -up -down"
	exit 1
fi

DISP_CNT="$(xrandr -q | grep " connected" | cut -d ' ' -f1 | wc -l)"
if [ "$DISP_CNT" == 1 ]; then
	xrandr --output LVDS1 --brightness 1.0
	BRIGHTNESS="$(xbacklight)"
	MULT="100"
else
	xbacklight -set 100
	BRIGHTNESS=$(xrandr --verbose | grep -i brightness | grep -o "[0-9]\.[0-9]*" | head -n 1)
	MULT="1"
fi



case "$1" in
	"-up")
		NEWBR=$(echo "$BRIGHTNESS+(0.1*$MULT)" | bc -l | awk '{printf "%f", $0}')

		if [ "$(echo "$NEWBR > (1*$MULT)" | bc)" == "1" ]; then
			NEWBR="$(echo "1.0*$MULT" | bc -l | egrep -o '[0-9]{1,3}\.[0-9]')"
		fi

		;;
	"-down")
		NEWBR=$(echo "$BRIGHTNESS-(0.1*$MULT)" | bc -l | awk '{printf "%f", $0}')
		if [ "$(echo "$NEWBR < 0" | bc)" == "1" ]; then
			NEWBR=0.0
		fi

		;;
	*)
		echo "Usage: $0 -up -down"
		exit 1
	;;
esac

if [ "$DISP_CNT" == 1 ]; then
	xbacklight -set "$NEWBR"
else
	for DISP in $(xrandr -q | grep ' connected' | cut -d ' ' -f1); do
		xrandr --output "$DISP" --brightness "$NEWBR"
	done
fi

ID=1235444

dunstify -r $ID -a sbright -p "Brightness: $(printf %d $(echo "($NEWBR/10)*10" | bc -l))%"
